version: '3'

services:
  app:
    build:
      context: .
      dockerfile: './Dockerfile'
    working_dir: '/var/www/app'
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - next-app

networks:
    next-app:
        driver: bridge