version: '3'

services:
  app:
    build:
      context: .
      dockerfile: './Dockerfile'
    working_dir: '/var/www/app'
    volumes:
      - ./pages:/var/www/app/pages
      - ./src:/var/www/app/src
      - ./public:/var/www/app/public
      - ./styles:/var/www/app/styles
    ports:
      - 3000:3000
    expose:
      - 3000
